### ISSUE TITLE
peripheral mac address not unique

### ISSUE THREAD

**Issue by srtianxia** [googlesamples/android-BluetoothAdvertisements#3]
Hello,I use the `BluetoothLeScanner`  device to search `BluetoothLeAdvertiser` device.**I only use the same peripheral device(an android phone)**. But I try many times, the `BluetoothLeScanner` device search the different mac address every time. I use the callback `onScanResult()` and the function `result.getDevice().getAddress()`

``` java
@Override public void onScanResult(int callbackType, ScanResult result) {
            super.onScanResult(callbackType, result);
            if (mOnScanCallback != null) {
                Logger.i("ScanResult" + result.getDevice().getAddress());
            }
        }
```

**Comment by hammmmy** [comment]
When LE privacy (https://blog.bluetooth.com/bluetooth-technology-protecting-your-privacy) is in use the mac addresses are randomized and they maybe different from the BD_ADDR.  Thats what seems to be happening on your Android Phone which you are using as a Peripheral.

**Comment by jamesweb1** [comment]
Hi, I feel frustrated of the Mac address rotating in my phone. I use two phones as scanner and advertiser. Why do I see the exact persistent Mac address of advertise phone in the scanner phone and do not see any rotating Mac address?

**Comment by srtianxia** [comment]
@jamesweb1  I mean the same device, which shows different mac address on two broadcasts.
